# ============================================================================
#  Makefile
# ============================================================================

#  Author:         (c) 2005 Camil Demetrescu, Andrew Goldberg
#  License:        See the end of this file for license information
#  Created:        November 15, 2005
 
#  Last changed:   $Date: 2005/11/15 11:50:52 $
#  Changed by:     $Author: demetres $
#  Revision:       $Revision: 1.1 $

#  9th DIMACS Implementation Challenge: Shortest Paths
#  http://www.dis.uniroma1.it/~challenge9

#  Usage: > make        (Builds up the core solvers)
#  Usage: > make clean  (Cleans up the core solvers)

all: 
	cd ./mlb-dimacs; $(MAKE)

clean:
	cd ./mlb-dimacs; $(MAKE) clean

# Copyright (C) 2005 Camil Demetrescu, Andrew Goldberg

 #  This program is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
 #  the Free Software Foundation; either version 2 of the License, or
 #  (at your option) any later version.

 #  This program is distributed in the hope that it will be useful,
 #  but WITHOUT ANY WARRANTY; without even the implied warranty of
 #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #  GNU General Public License for more details.

 #  You should have received a copy of the GNU General Public License
 #  along with this program; if not, write to the Free Software
 #  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA 
 